
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa",
 "version": "0.9.2+75.g4b901f6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
